app/activities/__init__.py
from flask import Blueprint

bp = Blueprint('activities', __name__)

from app.activities import routes

app/activities/routes.py
from flask import render_template, request
from flask_login import login_required, current_user
from app import db
from app.activities import bp


@bp.route('/exercises')
@login_required
def exercises():
    return render_template('activities/exercises.html', title='Exercises', user=current_user, points=current_user.points)


@bp.route('/activity4')
@login_required
def activity4():
    return render_template('activities/activity4.html', title='Activity 4', user=current_user, points=current_user.points)


@bp.route('/activity6')
@login_required
def activity6():
    return render_template('activities/activity6.html', title='Activity 6', user=current_user, points=current_user.points)


@bp.route('/activity101')
@login_required
def activity101():
    return render_template('activities/activity101.html', title='Activity 1', user=current_user, points=current_user.points)


@bp.route('/activity2')
@login_required
def activity2():
    return render_template('activities/activity2.html', title='Activity 2', user=current_user, points=current_user.points)


@bp.route('/activity2_classical')
@login_required
def activity2_classical():
    return render_template('activities/activity2_classical.html', title='Classical Music', user=current_user,
                           points=current_user.points)


@bp.route('/activity2_stringed')
@login_required
def activity2_stringed():
    return render_template('activities/activity2_stringed.html', title='String Music', user=current_user,
                           points=current_user.points)


@bp.route('/activity2_piano')
@login_required
def activity2_piano():
    return render_template('activities/activity2_piano.html', title='Music: Piano', user=current_user, points=current_user.points)


@bp.route('/activity2_wind')
@login_required
def activity2_wind():
    return render_template('activities/activity2_wind.html', title='Wind Music', user=current_user, points=current_user.points)


@bp.route('/activity2_natural')
@login_required
def activity2_natural():
    return render_template('activities/activity2_natural.html', title='Natural Sound', user=current_user,
                           points=current_user.points)


@bp.route('/activity2_popular')
@login_required
def activity2_popular():
    return render_template('activities/activity2_popular.html', title='Popular Music', user=current_user,
                           points=current_user.points)


@bp.route('/activity5')
@login_required
def activity5():
    return render_template('activities/activity5.html', title='Activity 5', user=current_user, points=current_user.points)


@bp.route('/activity1')
@login_required
def activity1():
    return render_template('activities/activity1.html', title='Activity 1', user=current_user, points=current_user.points)


# @bp.route('/activity4')
# @login_required
# def activity4():
#     return render_template('activities/activity4.html', title='Activity 4')


# @bp.route('/activity6')
# @login_required
# def activity6():
#     return render_template('activities/activity6.html', title='Activity 6')

app/templates/activities/activity2.html
<!DOCTYPE html>
{% extends "base.html"%}
{% block content %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.musicTop{
  background-image: url('https://get.pxhere.com/photo/laptop-computer-macbook-apple-music-black-and-white-keyboard-white-photography-guitar-band-microphone-studio-black-monochrome-musical-instrument-drawing-hands-audio-photograph-sound-musicians-image-instruments-shape-cymbal-monochrome-photography-string-instrument-atmosphere-of-earth-plucked-string-instruments-electric-guitars-accoustin-guitar-cymbols-762408.jpg');
  background-repeat: no-repeat;
  background-size: 100% 100%;
  -moz-background-size: 100% 100%;

}
.mask{
           position: relative;
           width:100%;
           height:100%;
           overflow: hidden;
       }
       .mask:after{
           content: attr(data-title);
           position: absolute;
           width:100%;
           top:100%;
           left:0;
           padding: 0.7em 0;
           text-align: center;
           color: #fff;
           background-color: rgba(52,47,41,.5);
           -webkit-transition:all .3s ease-in-out;
           transition:all .3s ease-in-out;
           opacity: 0;
       }
       .mask:hover:after{
           opacity: 1;
           -webkit-transform:translate(0,-100%);
           transform:translate(0,-100%);
       }

</style>
<body>

<div class="jumbotron musicTop">
  <div class="container text-center">
    <h2>&nbsp;&nbsp; </h2>
    <h2 class="w3-text-dark-grey w3-xxlarge" style="font-style: oblique;">Listening to relaxing music&nbsp;&nbsp;</h2>
    <h2>&nbsp;&nbsp; </h2>
    <h2>&nbsp;&nbsp; </h2>
  </div>
  </div>
</div>
<div class="container">
<h2 class="container-fluid w3-text-dark-grey"style="margin-bottom: 30px;margin-top: 25px;"> Recommendation&nbsp;&nbsp;<span class="glyphicon glyphicon-music" style=""></span></h2>
<div class="row">
    <div class="col-md-4">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/6768788&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
    </div>
    <div class="col-md-4">
      <iframe width="100%" height="177" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/9123875&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
    </div>
    <div class="col-md-4">
      <iframe width="100%" height="177" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/435378582&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
    </div>
</div>
</div>

<div class="container">
<h2 class="container-fluid w3-text-dark-grey"style="margin-bottom: 30px;margin-top: 50px;"> Categories&nbsp;&nbsp;<span class="glyphicon glyphicon-music" style=""></span></h2>
<div class="w3-main" style="">
<div class="w3-row">
    <div class="w3-third">
      <div class="mask" data-title="Classical">
      <a href="{{url_for('activities.activity2_classical')}}">
      <img src="https://get.pxhere.com/photo/music-people-wood-guitar-acoustic-guitar-jeans-instrument-hat-musician-musical-instrument-shooting-ukulele-musical-classic-guitarist-games-banjo-firearm-string-instrument-plucked-string-instruments-paneling-country-song-965005.jpg" style="width:100%">
    </a>
    </div>


      <div class="mask" data-title="Stringed Instrument Music">
      <a href="{{url_for('activities.activity2_stringed')}}">
      <img src="https://get.pxhere.com/photo/rock-record-music-wood-retro-guitar-string-acoustic-guitar-concert-band-equipment-instrument-recording-studio-artist-blue-professional-playing-performer-musician-black-player-acoustic-electric-guitar-musical-instrument-jazz-recording-classical-audio-musical-bassist-wooden-sound-classic-guitarist-song-bass-guitar-folk-melody-classical-guitar-singer-songwriter-string-instrument-plucked-string-instruments-slide-guitar-acoustic-electric-guitar-jazz-guitarist-732161.jpg" style="width:100%"></a>
    </div>

    </div>

    <div class="w3-third">
      <div class="mask" data-title="Piano">
      <a href="{{url_for('activities.activity2_piano')}}">
      <img src="https://get.pxhere.com/photo/hand-music-black-and-white-keyboard-technology-old-piano-musician-monochrome-musical-instrument-skin-pianist-monochrome-photography-string-instrument-electronic-device-musical-keyboard-electric-piano-player-piano-jazz-pianist-45000.jpg"style="width:100%">
      </a>
      </div>

      <div class="mask" data-title="Wind Music">
      <a href="{{url_for('activities.activity2_wind')}}">
      <img src="https://get.pxhere.com/photo/music-reflection-instrument-musical-instrument-saxophone-gold-brass-keys-classic-trumpet-gloss-section-wind-instrument-notenblatt-classical-music-music-band-brass-instrument-woodwind-instrument-western-concert-flute-reed-instrument-euphonium-770125.jpg" style="width:100%">
    </a>
    </div>
    </div>

    <div class="w3-third">
        <div class="mask" data-title="Popular">
          <a href="{{url_for('activities.activity2_popular')}}">
            <img src="https://get.pxhere.com/photo/music-technology-white-equipment-studio-gadget-ear-lifestyle-dj-radio-human-body-stereo-fun-audio-headphones-musical-organ-song-listen-entertainment-enjoying-listening-mp3-audio-equipment-sounds-electronic-device-714531.jpg"style="width:100%">
          </a>
        </div>
    <div class="mask" data-title="Natural Sound">
      <a href="{{url_for('activities.activity2_natural')}}">
      <img src="https://get.pxhere.com/photo/record-music-vinyl-turntable-black-and-white-technology-white-photography-vintage-plastic-reflection-gadget-black-monochrome-stylus-record-player-close-up-brand-mono-sound-data-macro-photography-monochrome-photography-phonograph-record-1175483.jpg" style="width:100%">
    </a>
    </div>
    </div>

  </div>
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c98026c2355556d"></script>
</html>
{% endblock %}

app/templates/activities/activity2_classical.html
<!DOCTYPE html>
{% extends "base.html"%}
{% block content %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.musicTop{
  background-image: url('https://get.pxhere.com/photo/nature-sky-wilderness-mountainous-landforms-mountain-mount-scenery-morning-national-park-sunlight-photography-hill-hill-station-ridge-mountain-range-highland-atmosphere-grass-panorama-dawn-landscape-terrain-horizon-forest-tree-computer-wallpaper-escarpment-valley-cloud-meadow-1438043.jpg');
  background-repeat: no-repeat;
  background-size: 100% 100%;
  -moz-background-size: 100% 100%;
}
</style>
<body>
<div class="jumbotron musicTop">
  <div class="container text-center">
    <h2>&nbsp;&nbsp; </h2>
    <h2 class="w3-text-dark-grey w3-xxlarge" style="font-style: oblique;">&nbsp;&nbsp;</h2>
    <h2>&nbsp;&nbsp; </h2>
    <h2>&nbsp;&nbsp; </h2>
  </div>
  </div>
</div>
<div class="container">
<h2 class="w3-text-dark-grey"style="margin-bottom: 20px;margin-top: 25px;"> Classical&nbsp;&nbsp;<span class="glyphicon glyphicon-music" style=""></span></h2>
<div class="row">
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/56754571&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/58122289&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/81524116&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/78673940&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/155469367&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/155469656&color=%23239ac3&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"style="margin-bottom: 20px;margin-top: 20px;"></iframe>
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c98026c2355556d"></script>
</html>
{% endblock %}

app/templates/activities/exercises.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block head %}
	<script>
	function toggle(input)//input can be 'vision', 'hearing', 'speech'.
	{
		var currButton = document.getElementById(input+'-toggle');
		if(currButton.getAttribute('aria-pressed') == 'false')
		{
			var allElems = document.getElementsByClassName(input);
			for (var i = 0; i <allElems.length; i++)
			{
				allElems[i].style.display = 'none';
			}
			if(input == 'vision'){currButton.innerHTML = ' Show Acivities that Require Vision ';}
			else if(input == 'hearing'){currButton.innerHTML = ' Show Acivities that Require Hearing ';}
			else{currButton.innerHTML = ' Show Acivities that Require Speech ';}

			currButton.style.background = '#41658A';
			currButton.style.color = '#FFFFFF';
		}
		else
		{
			var allElems = document.getElementsByClassName(input);
			for (var i = 0; i <allElems.length; i++)
			{
				allElems[i].style.display = 'block';
			}
			if(input == 'vision'){currButton.innerHTML = ' Hide Acivities that Require Vision ';}
			else if(input == 'hearing'){currButton.innerHTML = ' Hide Acivities that Require Hearing ';}
			else{currButton.innerHTML = ' Hide Acivities that Require Speech ';}

			currButton.style.background = '#FFFFFF';
			currButton.style.color = '#000000';
		}

	}
	</script>
{% endblock %}

{% block content %}
<div class="container" style="padding: 5%; margin: auto; font-family: 'Merriweather', serif;">

  <div class="row" style="padding: 0;">
	<div class="col-md-12" style="text-align: center;">
		<h1>Exercises</h1>
	</div>
  </div>


  <div class="row" style="padding: 2%;">
	<div class="col-md-12" style="text-align: center;">
		<div class="btn-group">
			<button id="vision-toggle" type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onclick="toggle('vision')" style="background-color: #FFFFFF; color: #000000;"> Hide Acivities that Require Vision </button>
			<button id="hearing-toggle" type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onclick="toggle('hearing')" style="background-color: #FFFFFF; color: #000000;"> Hide Acivities that Require Hearing </button>
			<button id="speech-toggle" type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onclick="toggle('speech')" style="background-color: #FFFFFF; color: #000000;"> Hide Acivities that Require Speech </button>
		</div>
	</div>
  </div>


  <div class="row" style="padding: 5%; padding-bottom: 2%;">





	<div class="col-md-3" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg1.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title">Tame Your Stress</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity1')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg3.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i> Relaxing Music</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg4.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i>  Relaxing Music - Classical</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_classical')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg5.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i>  Relaxing Music - Strings</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_stringed')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg7.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i> Relaxing Music - Piano</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_piano')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg8.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i> Relaxing Music - Wind</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_wind')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg9.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i> Relaxing Music - Natural</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_natural')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-3 hearing" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg10.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="fas fa-headphones"></i> Relaxing Music - Popular</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity2_popular')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-3" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg17.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title">Self Care Test</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity4')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-3 vision" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg12.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title"><i class="far fa-eye"></i>Video Assisted Meditation</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity5')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-3" style="padding-bottom: 5%;">
		<div class="card">
			<img class="card-img-top" src="{{ url_for('static', filename='bg13.jpg') }}" alt="Card image" style="width:100%; padding-left: 0; padding-right: 0;">
			<div class="card-body" style="text-align: center;">
				<h4 class="card-title">Text Assisted Meditation</h4>
				<div class="progress">
					<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%; background-color:#41658A;">
					</div>
				</div>
				<div style="padding-top: 7%;">
					<a href="{{url_for('activities.activity6')}}" class="btn" style="background-color: #41658A; color:#FFFFFF;">Go!</a>
				</div>
			</div>
		</div>
	</div>


  </div>

</div>
{% endblock %}